{% set name = "inline-sql" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inline_sql-{{ version }}.tar.gz
  sha256: c0ad4826c1eb243dbcfcb1958a94191578d65bddc3a26633c60862062a86612d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - pandas >=1.3.5,<1.4.dev0
    - python >={{ python_min }}
    - python-duckdb >=0.5.1,<0.6.dev0
    - sqlparse >=0.4.3,<0.5.dev0

test:
  imports:
    - inline_sql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ekzhang/inline-sql
  summary: Inline SQL in any Python program, on local dataframes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
